language: python
python:
  - '3.6'
  - '3.5'
  - '3.4'

sudo: false

install:
  - pip install -r requirements_test.txt

script:
  - python -m pytest test/ --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing

after_success:
  - coveralls