language: python
python:
  - '3.6'
  - '3.5'
  - '3.4'

sudo: false

install:
  - pip install -r requirements_test.txt

script:
  - python -m pytest --doctest-modules -v --cov xcomfort --cov-report term-missing

after_success:
  - coveralls